name: $(date:yyyyMMdd)$(rev:.r)

schedules:
- cron: "0 0 1 * *"
  displayName: Run At 00:00 on day-of-month 1
  branches:
    include:
    - main

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildNumber)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: 'Dockerhub'
        repository: 'spy86/ansible'
        command: 'build'
        Dockerfile: '**/Dockerfile'
        tags: '$(tag)'
    - task: Docker@2
      displayName: Push an image
      inputs:
        containerRegistry: 'Dockerhub'
        repository: 'spy86/ansible'
        command: 'push'
        tags: '$(tag)'

- stage: Build_Latest_tag
  dependsOn: [Build]
  displayName: Rebuild an latest image
  jobs:
  - job: Build_latest_tag
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: 'Dockerhub'
        repository: 'spy86/ansible'
        command: 'build'
        Dockerfile: '**/Dockerfile'
        tags: 'latest'
    - task: Docker@2
      displayName: Push an image
      inputs:
        containerRegistry: 'Dockerhub'
        repository: 'spy86/ansible'
        command: 'push'
        tags: 'latest'