name: $(date:yyyyMMdd)$(rev:.r)

parameters:
- name: TestBuild
  displayName: 'Test Build ???'
  type: string
  default: 'false'
  values:
    - true
    - false

schedules:
- cron: "0 0 1 * *"
  displayName: Run At 00:00 on day-of-month 1
  branches:
    include:
    - main

trigger:
- main

resources:
- repo: self

variables:
  - name: TestBuild
    value: ${{parameters.TestBuild}}
  - name: tag
    value: '$(Build.BuildNumber)'
  - name: image_name
    value: 'ansible'


stages:
- stage: Build
  condition: eq('${{variables.TestBuild}}', 'false')
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: 'Dockerhub'
        repository: 'spy86/$(image_name)'
        command: 'build'
        Dockerfile: '**/Dockerfile'
        tags: '$(tag)'
    - task: Docker@2
      displayName: Push an image
      inputs:
        containerRegistry: 'Dockerhub'
        repository: 'spy86/$(image_name)'
        command: 'push'
        tags: '$(tag)'

- stage: Build_Latest_tag
  condition: eq('${{variables.TestBuild}}', 'false')
  dependsOn: [Build]
  displayName: Rebuild an latest image
  jobs:
  - job: Build_latest_tag
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: 'Dockerhub'
        repository: 'spy86/$(image_name)'
        command: 'build'
        Dockerfile: '**/Dockerfile'
        tags: 'latest'
    - task: Docker@2
      displayName: Push an image
      inputs:
        containerRegistry: 'Dockerhub'
        repository: 'spy86/$(image_name)'
        command: 'push'
        tags: 'latest'

- stage: Test_Build
  condition: eq('${{variables.TestBuild}}', 'true')
  displayName: Test Build
  jobs:
  - job: Test_Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: 'Dockerhub'
        repository: 'spy86/$(image_name)'
        command: 'build'
        Dockerfile: '**/Dockerfile'
        tags: 'latest'